export type DeepColors = 'blue' | 'purple' | 'green' | 'orange' | 'emerald' | 'pink' | 'fuchsia'
  | 'gray' | 'cyan' | 'red' | 'yellow' | 'lime' | 'sky' | 'amber' | 'indigo' | 'violet' | 'rose';

interface ColorClassSet {
  text: string;
  textMuted: string;
  bg: string;
  bgHover: string;
  border: string;
  borderFocus: string;
  ringFocus: string;
  hoverText: string;
  hoverBg: string;
  peerFocusRing300: string;
  peerCheckedBg600: string;
}

export const colorClassMap: Record<DeepColors, ColorClassSet> = {
  blue: {
    text: 'text-blue-500',
    textMuted: 'text-blue-700',
    bg: 'bg-blue-50',
    bgHover: 'hover:bg-blue-100',
    border: 'border-blue-200',
    borderFocus: 'focus:border-blue-300',
    ringFocus: 'focus:ring-blue-300',
    hoverText: 'hover:text-blue-500',
    hoverBg: 'hover:bg-blue-50',
    peerFocusRing300: 'peer-focus:ring-blue-300',
    peerCheckedBg600: 'peer-checked:bg-blue-600',
  },
  pink: {
    text: 'text-pink-500',
    textMuted: 'text-pink-700',
    bg: 'bg-pink-50',
    bgHover: 'hover:bg-pink-100',
    border: 'border-pink-200',
    borderFocus: 'focus:border-pink-300',
    ringFocus: 'focus:ring-pink-300',
    hoverText: 'hover:text-pink-500',
    hoverBg: 'hover:bg-pink-50',
    peerFocusRing300: 'peer-focus:ring-pink-300',
    peerCheckedBg600: 'peer-checked:bg-pink-600',
  },
  fuchsia: {
    text: 'text-fuchsia-500',
    textMuted: 'text-fuchsia-700',
    bg: 'bg-fuchsia-50',
    bgHover: 'hover:bg-fuchsia-100',
    border: 'border-fuchsia-200',
    borderFocus: 'focus:border-fuchsia-300',
    ringFocus: 'focus:ring-fuchsia-300',
    hoverText: 'hover:text-fuchsia-500',
    hoverBg: 'hover:bg-fuchsia-50',
    peerFocusRing300: 'peer-focus:ring-fuchsia-300',
    peerCheckedBg600: 'peer-checked:bg-fuchsia-600',
  },
  indigo: {
    text: 'text-indigo-500',
    textMuted: 'text-indigo-700',
    bg: 'bg-indigo-50',
    bgHover: 'hover:bg-indigo-100',
    border: 'border-indigo-200',
    borderFocus: 'focus:border-indigo-300',
    ringFocus: 'focus:ring-indigo-300',
    hoverText: 'hover:text-indigo-500',
    hoverBg: 'hover:bg-indigo-50',
    peerFocusRing300: 'peer-focus:ring-indigo-300',
    peerCheckedBg600: 'peer-checked:bg-indigo-600',
  },
  violet: {
    text: 'text-violet-500',
    textMuted: 'text-violet-700',
    bg: 'bg-violet-50',
    bgHover: 'hover:bg-violet-100',
    border: 'border-violet-200',
    borderFocus: 'focus:border-violet-300',
    ringFocus: 'focus:ring-violet-300',
    hoverText: 'hover:text-violet-500',
    hoverBg: 'hover:bg-violet-50',
    peerFocusRing300: 'peer-focus:ring-violet-300',
    peerCheckedBg600: 'peer-checked:bg-violet-600',
  },
  rose: {
    text: 'text-rose-500',
    textMuted: 'text-rose-700',
    bg: 'bg-rose-50',
    bgHover: 'hover:bg-rose-100',
    border: 'border-rose-200',
    borderFocus: 'focus:border-rose-300',
    ringFocus: 'focus:ring-rose-300',
    hoverText: 'hover:text-rose-500',
    hoverBg: 'hover:bg-rose-50',
    peerFocusRing300: 'peer-focus:ring-rose-300',
    peerCheckedBg600: 'peer-checked:bg-rose-600',
  },
  emerald: {
    text: 'text-emerald-500',
    textMuted: 'text-emerald-700',
    bg: 'bg-emerald-50',
    bgHover: 'hover:bg-emerald-100',
    border: 'border-emerald-200',
    borderFocus: 'focus:border-emerald-300',
    ringFocus: 'focus:ring-emerald-300',
    hoverText: 'hover:text-emerald-500',
    hoverBg: 'hover:bg-emerald-50',
    peerFocusRing300: 'peer-focus:ring-emerald-300',
    peerCheckedBg600: 'peer-checked:bg-emerald-600',
  },
  amber: {
    text: 'text-amber-500',
    textMuted: 'text-amber-700',
    bg: 'bg-amber-50',
    bgHover: 'hover:bg-amber-100',
    border: 'border-amber-200',
    borderFocus: 'focus:border-amber-300',
    ringFocus: 'focus:ring-amber-300',
    hoverText: 'hover:text-amber-500',
    hoverBg: 'hover:bg-amber-50',
    peerFocusRing300: 'peer-focus:ring-amber-300',
    peerCheckedBg600: 'peer-checked:bg-amber-600',
  },
  sky: {
    text: 'text-sky-500',
    textMuted: 'text-sky-700',
    bg: 'bg-sky-50',
    bgHover: 'hover:bg-sky-100',
    border: 'border-sky-200',
    borderFocus: 'focus:border-sky-300',
    ringFocus: 'focus:ring-sky-300',
    hoverText: 'hover:text-sky-500',
    hoverBg: 'hover:bg-sky-50',
    peerFocusRing300: 'peer-focus:ring-sky-300',
    peerCheckedBg600: 'peer-checked:bg-sky-600',
  },
  purple: {
    text: 'text-purple-500',
    textMuted: 'text-purple-700',
    bg: 'bg-purple-50',
    bgHover: 'hover:bg-purple-100',
    border: 'border-purple-200',
    borderFocus: 'focus:border-purple-300',
    ringFocus: 'focus:ring-purple-300',
    hoverText: 'hover:text-purple-500',
    hoverBg: 'hover:bg-purple-50',
    peerFocusRing300: 'peer-focus:ring-purple-300',
    peerCheckedBg600: 'peer-checked:bg-purple-600',
  },
  green: {
    text: 'text-green-500',
    textMuted: 'text-green-700',
    bg: 'bg-green-50',
    bgHover: 'hover:bg-green-100',
    border: 'border-green-200',
    borderFocus: 'focus:border-green-300',
    ringFocus: 'focus:ring-green-300',
    hoverText: 'hover:text-green-500',
    hoverBg: 'hover:bg-green-50',
    peerFocusRing300: 'peer-focus:ring-green-300',
    peerCheckedBg600: 'peer-checked:bg-green-600',
  },
  orange: {
    text: 'text-orange-500',
    textMuted: 'text-orange-700',
    bg: 'bg-orange-50',
    bgHover: 'hover:bg-orange-100',
    border: 'border-orange-200',
    borderFocus: 'focus:border-orange-300',
    ringFocus: 'focus:ring-orange-300',
    hoverText: 'hover:text-orange-500',
    hoverBg: 'hover:bg-orange-50',
    peerFocusRing300: 'peer-focus:ring-orange-300',
    peerCheckedBg600: 'peer-checked:bg-orange-600',
  },
  gray: {
    text: 'text-gray-500',
    textMuted: 'text-gray-700',
    bg: 'bg-gray-50',
    bgHover: 'hover:bg-gray-100',
    border: 'border-gray-200',
    borderFocus: 'focus:border-gray-300',
    ringFocus: 'focus:ring-gray-300',
    hoverText: 'hover:text-gray-500',
    hoverBg: 'hover:bg-gray-50',
    peerFocusRing300: 'peer-focus:ring-gray-300',
    peerCheckedBg600: 'peer-checked:bg-gray-600',
  },
  cyan: {
    text: 'text-cyan-500',
    textMuted: 'text-cyan-700',
    bg: 'bg-cyan-50',
    bgHover: 'hover:bg-cyan-100',
    border: 'border-cyan-200',
    borderFocus: 'focus:border-cyan-300',
    ringFocus: 'focus:ring-cyan-300',
    hoverText: 'hover:text-cyan-500',
    hoverBg: 'hover:bg-cyan-50',
    peerFocusRing300: 'peer-focus:ring-cyan-300',
    peerCheckedBg600: 'peer-checked:bg-cyan-600',
  },
  red: {
    text: 'text-red-500',
    textMuted: 'text-red-700',
    bg: 'bg-red-50',
    bgHover: 'hover:bg-red-100',
    border: 'border-red-200',
    borderFocus: 'focus:border-red-300',
    ringFocus: 'focus:ring-red-300',
    hoverText: 'hover:text-red-500',
    hoverBg: 'hover:bg-red-50',
    peerFocusRing300: 'peer-focus:ring-red-300',
    peerCheckedBg600: 'peer-checked:bg-red-600',
  },
  yellow: {
    text: 'text-yellow-500',
    textMuted: 'text-yellow-700',
    bg: 'bg-yellow-50',
    bgHover: 'hover:bg-yellow-100',
    border: 'border-yellow-200',
    borderFocus: 'focus:border-yellow-300',
    ringFocus: 'focus:ring-yellow-300',
    hoverText: 'hover:text-yellow-500',
    hoverBg: 'hover:bg-yellow-50',
    peerFocusRing300: 'peer-focus:ring-yellow-300',
    peerCheckedBg600: 'peer-checked:bg-yellow-600',
  },
  lime: {
    text: 'text-lime-500',
    textMuted: 'text-lime-700',
    bg: 'bg-lime-50',
    bgHover: 'hover:bg-lime-100',
    border: 'border-lime-200',
    borderFocus: 'focus:border-lime-300',
    ringFocus: 'focus:ring-lime-300',
    hoverText: 'hover:text-lime-500',
    hoverBg: 'hover:bg-lime-50',
    peerFocusRing300: 'peer-focus:ring-lime-300',
    peerCheckedBg600: 'peer-checked:bg-lime-600',
  },
};
